#!/bin/bash

echo "🔒 Setting up HTTPS for Spotify OAuth..."
echo ""
echo "✅ SSL certificates have been generated in ./certificates/"
echo ""
echo "📋 Next steps:"
echo ""
echo "1. Update your Spotify App settings:"
echo "   - Go to https://developer.spotify.com/dashboard"
echo "   - Select your app (AI Muzak)"
echo "   - Go to Settings"
echo "   - Add this redirect URI:"
echo "     https://localhost:3000/api/auth/callback/spotify"
echo "   - Save the changes"
echo ""
echo "2. Start the development server:"
echo "   npm run dev"
echo ""
echo "3. When you visit https://localhost:3000 in your browser:"
echo "   - You'll see a security warning (this is normal for self-signed certificates)"
echo "   - Click 'Advanced' and then 'Proceed to localhost (unsafe)'"
echo "   - The browser will remember this exception"
echo ""
echo "✨ You're all set! The app will now work with Spotify OAuth over HTTPS."